#!/bin/bash
packages=("amd-ucode")
packages+=("efibootmgr") #For EFISTUB
packages+=("pavucontrol") #For audio control
packages+=("firefox") #Web browser
packages+=("mpv") #MPV as multimidia player
packages+=("nodejs-lts-jod" "npm" "rust") #Programming languages
packages+=("keepassxc") #Password manager
packages+=("noto-fonts" "ttf-nerd-fonts-symbols" "noto-fonts-emoji" "adobe-source-han-sans-otc-fonts" "gnu-free-fonts") #Fonts
packages+=("7zip") #For handling archives
packages+=("yt-dlp") #For downloading youtube videos and other sites
packages+=("man-db") #Commands manual
packages+=("lm_sensors") #Sensors command
packages+=("dunst") #Desktop notifications
packages+=("opendoas") #Instead of sudo
packages+=("htop") #Process viewer
packages+=("bash-completion")
packages+=("base-devel" "exfatprogs" "rsync" "fd" "ripgrep" "prettier" "stow" "skim")
packages+=("pacman-contrib" "cryptsetup" "polkit")
packages+=("fuzzel" "waybar" "chromium" "udisks2" "bc" "openssh" "gamemode" "mesa-utils" "mangohud")
packages+=("swaylock" "swayidle" "foot" "pipewire" "pipewire-pulse" "wireplumber" "qt5-wayland")
packages+=("xorg-xwayland" "xorg-server" "xorg-setxkbmap" "xorg-xset" "xorg-xrandr" "xorg-xinit" "xorg-xrdb" "xorg-xprop" "xorg-xinput")
packages+=("iwd" "dhcpcd")

pacman -S --needed ${packages[*]}
pacman -Rnsdd sudo
