#!/bin/bash
cd "$(dirname $0)"
source "./utils/ask"

echo "Set timezone. Use full path."
ask "" "/usr/share/zoneinfo/America/Sao_Paulo" 
ln -sfv "$REPLY" /etc/localtime
hwclock --systohc

echo "Uncomment a locale to be used."
read -e -p "[ENTER to open nvim into /etc/locale.gen]: "
nvim /etc/locale.gen
locale-gen

echo "Set your LANG variable. Your available locales:"
grep '^[^#]' /etc/locale.gen
ask "" "en_US.UTF-8"
echo "LANG=$REPLY" > /etc/locale.conf

echo "Set the console keyboard layout."
ask "" "br-abnt2"
echo "KEYMAP=$REPLY" > /etc/vconsole.conf

echo "Set your hostname."
ask "" "Buttscratcher"
echo "$REPLY" > /etc/hostname

#/etc/hosts
echo "127.0.0.1 localhost" > /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 $REPLY" >> /etc/hosts

echo "Set root password."
passwd

echo "Choose a name for the new user."
ask "" "bieel1503"
useradd -m -G wheel,disk,video "$REPLY"
USER="$REPLY"
HOME="/home/$REPLY"

echo "Now set a password for the user."
passwd $REPLY

echo " "
echo "Install packages?"
ask "yes/no " "yes"

if [[ "$REPLY" == "yes" ]]; then

  source "./utils/installpackages"
  
fi

echo " "
echo "Set X11 mouse acceleration setting?"
ask "yes/no " "no"

if [[ "$REPLY" == "yes" ]]; then
  FILEPATH="/etc/X11/xorg.conf.d/"
  mkdir -p $FILEPATH
  cp "./utils/configs/50-mouse-acceleration.conf" $FILEPATH
fi

echo "Set X11 touchpad setting?"
ask "yes/no " "no"

if [[ "$REPLY" == "yes" ]]; then
  FILEPATH="/etc/X11/xorg.conf.d/"
  mkdir -p $FILEPATH
  cp "./utils/configs/30-touchpad.conf" $FILEPATH
fi

echo "Activate numlock on getty?"
ask "yes/no " "yes"

if [[ "$REPLY" == "yes" ]]; then
  FILEPATH="/etc/systemd/system/getty@.service.d/"
  mkdir -p $FILEPATH
  cp "./utils/configs/activate-numlock.conf" $FILEPATH
fi

echo " "
echo "blacklist pcspkr" > "/etc/modprobe.d/nobeep.conf"
echo "Blacklisted annoying beep sound."

cp "./utils/configs/99-sysctl.conf" "/etc/sysctl.d/"
echo "Added sysctl config file."

echo "permit persist :wheel" > /etc/doas.conf
echo "Created 'doas.conf' file."

ln -sv /usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf /etc/fonts/conf.d/

mv -f "./utils/configs/iptables.rules" "/etc/iptables/"
systemctl enable iptables
echo "Moved iptables rules file and enabled iptables service."
